# variables
@hostname = httpbin.org
@lat = {{>> ./env.sh lat}}
@lon = {{>> ./env.sh lon}}

@cfg.timeout = 5000
@cfg.check_json_body = true

### GET Buienalarm
# local variable overrules global
@hostname = cdn-secure.buienalarm.nl
GET https://{{hostname}}/api/3.4/forecast.php
lat={{lat}}
lon={{lon}}
region=nl
unit=mm/u
cache-control: no-cache

--{%
local body = ctx.json_body()
  ctx.set("start", body.start)
  ctx.set("temp", body.temp)
--%}

###
# GET Buienradar
@hostname = gadgets.buienradar.nl
GET https://{{hostname}}/data/raintext
lat={{lat}}
lon={{lon}}
cache-control: no-cache


### GET
GET https://{{hostname}}/get
id={{start}}
accept: application/json

###
POST https://{{hostname}}/post
content-type: application/x-www-form-urlencoded
accept: application/json
x-test: {{start}}

start={{start}}&
temp={{temp}}


###
POST https://httpbin.org/post
content-type: application/json
accept: application/json

{
  "start": "{{start}}",
  "temp": "{{temp}}"
}

